import google.generativeai as genai
import os

# genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
genai.configure(api_key="AIzaSyARM1uO0AelTAiAzwL6FhDH-WRrkKePPg4")

model = genai.GenerativeModel("gemini-2.0-flash")

def detect_high_level_categories():
    prompt = f'''
Give me a large text that looks like being scrapped from a tweets or news headlines or any other sorcees that contains a good amout of stats (numerical data)
the text must be of around 80000 words. And it must look realistic and not generated by AI. and note it should have numeriacal facts, you can make arrays for the text so that it looks like they are scrapped news from diiferent area.
It must have numerical data and stats in it. And the text should be in English language.
It should be easy that if i give my data to the modeel then we can create a good dataset from it.
'''
    response = model.generate_content(prompt)
    print("Response:", response.text.strip())
    try:
        categories = eval(response.text.strip())
        if isinstance(categories, list):
            return [c.strip().lower().replace(" ", "_") for c in categories]
    except Exception:
        pass
    return []

detect_high_level_categories()